---
- name: Configure RADIUS on Mikrotik CHR
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Add RADIUS server
      routeros_command:
        commands:
          - /radius add address=35.227.71.209 secret=testing123 service=hotspot
